import fs from 'fs';
import path from 'path';
import type { Rule } from './rule';
import {
  AGENTS_MD_FILE,
  AGENTS_MD_START,
  AGENTS_MD_END,
  SSOT_DIR,
  TOOL_NAME,
} from './constants';

/**
 * Writes an index of the rule set into the repo's AGENTS.md — a pointer, not
 * a copy.
 *
 * AGENTS.md is read natively by a long tail of agents this project will never
 * write a dedicated adapter for, so one file here reaches far more tools than
 * a seventh adapter would. What it deliberately does NOT do is inline the
 * rules themselves: a concatenated dump grows without bound as rules are
 * added and rides along in context every turn regardless of relevance. An
 * index stays a few lines per rule and lets the agent open only what matters,
 * which is what its own file-reading tools are for.
 *
 * Only the block between the markers is ever rewritten. AGENTS.md is
 * commonly hand-written, and anything outside the block belongs to the
 * author.
 */

function renderBlock(rules: Rule[]): string {
  const lines: string[] = [
    AGENTS_MD_START,
    `<!-- Generated by ${TOOL_NAME}. Edit the files in ${SSOT_DIR}/ instead, then run \`npx ${TOOL_NAME} sync\`. -->`,
    '',
    '## Project rules',
    '',
    `This project's coding rules live in \`${SSOT_DIR}/\`. Read the ones relevant to what`,
    'you are working on — each is listed below with the files it applies to.',
    '',
  ];

  if (rules.length === 0) {
    lines.push(`_No rules defined yet. Add one with \`npx ${TOOL_NAME} add\`._`);
  } else {
    for (const rule of sortRules(rules)) {
      const scope = rule.alwaysApply
        ? 'always applies'
        : `applies to \`${rule.globs.join('`, `')}\``;
      lines.push(`- \`${SSOT_DIR}/${toPosix(rule.relPath)}\` — ${rule.description} (${scope})`);
    }
  }

  lines.push('', AGENTS_MD_END);
  return lines.join('\n');
}

/** Stable ordering: always-apply rules first, then alphabetical by path. */
function sortRules(rules: Rule[]): Rule[] {
  return [...rules].sort((a, b) => {
    if (a.alwaysApply !== b.alwaysApply) return a.alwaysApply ? -1 : 1;
    return a.relPath.localeCompare(b.relPath);
  });
}

/** Paths in the index are for humans and agents to read, so always forward slashes. */
function toPosix(relPath: string): string {
  return relPath.split(path.sep).join('/');
}

/**
 * Adds, updates, or (when `enabled` is false) removes the managed block.
 *
 * Removing never deletes the file itself — an AGENTS.md the user wrote is
 * theirs, and this tool only ever owned the block inside it.
 */
export function updateAgentsMd(projectRoot: string, rules: Rule[], enabled: boolean): void {
  const target = path.join(projectRoot, AGENTS_MD_FILE);
  const exists = fs.existsSync(target);
  const existing = exists ? fs.readFileSync(target, 'utf8') : '';

  const startIndex = existing.indexOf(AGENTS_MD_START);
  const endIndex = existing.indexOf(AGENTS_MD_END);
  const hasBlock = startIndex !== -1 && endIndex !== -1 && endIndex > startIndex;

  const before = hasBlock ? existing.slice(0, startIndex).trimEnd() : existing.trimEnd();
  const after = hasBlock ? existing.slice(endIndex + AGENTS_MD_END.length).trimStart() : '';

  if (!enabled) {
    if (!hasBlock) return;
    const remaining = [before, after].filter(Boolean).join('\n\n');
    // An AGENTS.md that only ever held our block is ours to clean up; one with
    // the user's own content around it is not.
    if (remaining.trim().length === 0) {
      fs.unlinkSync(target);
    } else {
      fs.writeFileSync(target, `${remaining}\n`);
    }
    return;
  }

  const block = renderBlock(rules);
  const sections = hasBlock
    ? [before, block, after]
    : // A fresh file leads with the block; an existing one keeps its content
      // first and takes the block as an appendix.
      exists && before.length > 0
      ? [before, block]
      : [block];

  fs.writeFileSync(target, `${sections.filter(Boolean).join('\n\n')}\n`);
}
