import fs from 'fs';
import path from 'path';
import type { Rule } from './rule';
import {
  AGENTS_MD_FILE,
  AGENTS_MD_START,
  AGENTS_MD_END,
  AGENTS_MD_LEGACY_START,
  AGENTS_MD_LEGACY_END,
  CLAUDE_MD_FILE,
  SSOT_DIR,
  RULES_SUBDIR,
  SPECS_SUBDIR,
  TOOL_NAME,
} from './constants';

/**
 * Writes an index of the rule set into the repo's AGENTS.md, and into
 * CLAUDE.md for Claude Code — a pointer, not a copy.
 *
 * AGENTS.md is read natively by a long tail of agents this project will never
 * write a dedicated adapter for, so one file here reaches far more tools than
 * a seventh adapter would. What it deliberately does NOT do is inline the
 * rules themselves: a concatenated dump grows without bound as rules are
 * added and rides along in context every turn regardless of relevance. An
 * index stays a few lines per rule and lets the agent open only what matters,
 * which is what its own file-reading tools are for.
 *
 * Only the block between the markers is ever rewritten. Both files are
 * commonly hand-written, and anything outside the block belongs to the
 * author.
 */

interface BlockOptions {
  /**
   * Omit the rule listing and index only the specs.
   *
   * For CLAUDE.md when the `claude` adapter is active: those rules are already
   * compiled into `.claude/rules/` and load on their own, so listing them here
   * would send the same content twice. Specs have no such delivery path — the
   * index is the only way Claude Code learns they exist.
   */
  specsOnly?: boolean;
}

function renderBlock(rules: Rule[], specs: Rule[], options: BlockOptions = {}): string {
  const rulesDir = `${SSOT_DIR}/${RULES_SUBDIR}`;
  const specsDir = `${SSOT_DIR}/${SPECS_SUBDIR}`;

  const lines: string[] = [
    AGENTS_MD_START,
    `<!-- Generated by ${TOOL_NAME}. Edit the files in ${SSOT_DIR}/ instead, then run \`npx ${TOOL_NAME} sync\`. -->`,
  ];

  if (options.specsOnly) {
    lines.push(
      '',
      `<!-- Rules are compiled into .claude/rules/ and load automatically, so they are not repeated here. -->`,
    );
  } else {
    lines.push(
      '',
      '## Project rules',
      '',
      `This project's coding rules live in \`${rulesDir}/\`. Read the ones relevant to what`,
      'you are working on — each is listed below with the files it applies to.',
      '',
    );

    if (rules.length === 0) {
      lines.push(`_No rules defined yet. Add one with \`npx ${TOOL_NAME} add\`._`);
    } else {
      for (const rule of sortRules(rules)) {
        const scope = rule.alwaysApply
          ? 'always applies'
          : `applies to \`${rule.globs.join('\`, \`')}\``;
        lines.push(`- \`${rulesDir}/${toPosix(rule.relPath)}\` — ${rule.description} (${scope})`);
      }
    }
  }

  // Specs are listed, not copied. The full text stays in one place; an agent
  // reads the entry, decides whether it's relevant, and opens the file itself.
  if (specs.length > 0) {
    lines.push(
      '',
      '## Project specs',
      '',
      `Feature specs live in \`${specsDir}/\`. They are not loaded automatically —`,
      "open the one covering what you're working on.",
      '',
    );
    for (const spec of [...specs].sort((a, b) => a.relPath.localeCompare(b.relPath))) {
      const status = spec.status ? ` — ${spec.status}` : '';
      lines.push(`- \`${specsDir}/${toPosix(spec.relPath)}\` — ${spec.description}${status}`);
    }
  }

  lines.push('', AGENTS_MD_END);
  return lines.join('\n');
}

/** Stable ordering: always-apply rules first, then alphabetical by path. */
function sortRules(rules: Rule[]): Rule[] {
  return [...rules].sort((a, b) => {
    if (a.alwaysApply !== b.alwaysApply) return a.alwaysApply ? -1 : 1;
    return a.relPath.localeCompare(b.relPath);
  });
}

/** Paths in the index are for humans and agents to read, so always forward slashes. */
function toPosix(relPath: string): string {
  return relPath.split(path.sep).join('/');
}

/**
 * Finds the managed block, accepting the legacy markers as well as the
 * current ones so an upgrade replaces an older block instead of stranding it.
 * Returns the span to cut, or null when there's no block to replace.
 */
function locateBlock(existing: string): { start: number; end: number } | null {
  const pairs: [string, string][] = [
    [AGENTS_MD_START, AGENTS_MD_END],
    [AGENTS_MD_LEGACY_START, AGENTS_MD_LEGACY_END],
  ];

  for (const [startMarker, endMarker] of pairs) {
    const start = existing.indexOf(startMarker);
    const end = existing.indexOf(endMarker);
    if (start !== -1 && end !== -1 && end > start) {
      return { start, end: end + endMarker.length };
    }
  }
  return null;
}

/**
 * Adds, updates, or (when `enabled` is false) removes the managed block in one
 * file. Shared by AGENTS.md and CLAUDE.md, which differ only in their name and
 * what goes inside the block.
 *
 * Removing deletes the file only when the block was all it ever held. A file
 * the user wrote around our block is theirs.
 */
function writeManagedBlock(target: string, block: string, enabled: boolean): void {
  const exists = fs.existsSync(target);
  const existing = exists ? fs.readFileSync(target, 'utf8') : '';

  const found = locateBlock(existing);
  const hasBlock = found !== null;

  const before = found ? existing.slice(0, found.start).trimEnd() : existing.trimEnd();
  const after = found ? existing.slice(found.end).trimStart() : '';

  if (!enabled) {
    if (!hasBlock) return;
    const remaining = [before, after].filter(Boolean).join('\n\n');
    if (remaining.trim().length === 0) {
      fs.unlinkSync(target);
    } else {
      fs.writeFileSync(target, `${remaining}\n`);
    }
    return;
  }

  const sections = hasBlock
    ? [before, block, after]
    : // A fresh file leads with the block; an existing one keeps its content
      // first and takes the block as an appendix.
      exists && before.length > 0
      ? [before, block]
      : [block];

  fs.writeFileSync(target, `${sections.filter(Boolean).join('\n\n')}\n`);
}

export function updateAgentsMd(
  projectRoot: string,
  rules: Rule[],
  specs: Rule[],
  enabled: boolean,
): void {
  writeManagedBlock(
    path.join(projectRoot, AGENTS_MD_FILE),
    renderBlock(rules, specs),
    enabled,
  );
}

/**
 * The same block in CLAUDE.md, because Claude Code does not read AGENTS.md.
 *
 * `claudeAdapterActive` decides what goes in it, not whether to write it —
 * see `BlockOptions.specsOnly`.
 */
export function updateClaudeMd(
  projectRoot: string,
  rules: Rule[],
  specs: Rule[],
  enabled: boolean,
  claudeAdapterActive: boolean,
): void {
  writeManagedBlock(
    path.join(projectRoot, CLAUDE_MD_FILE),
    renderBlock(rules, specs, { specsOnly: claudeAdapterActive }),
    enabled,
  );
}
