/**
 * Single source of truth for every literal that identifies this tool on disk.
 *
 * Routing user-visible names through here means a future rename is a change to
 * these constants plus a watermark migration, rather than a find-and-replace
 * across every source file.
 */

export const TOOL_NAME = 'create-code-buddy';
export const TOOL_BIN = 'ccb';

/** Reported by `--version` when package.json can't be read at all. */
const UNKNOWN_VERSION = '0.0.0-unknown';

/**
 * The tool's version, read from package.json — the one place npm already
 * keeps authoritative.
 *
 * `--version` used to report a hardcoded '1.0.0' while package.json said
 * '1.0.0-beta.2', so the CLI claimed a version the package itself didn't.
 * Deliberately NOT an environment variable: there is no env at install time
 * that would carry this, so `npx create-code-buddy --version` would report
 * nothing for the people most likely to ask.
 *
 * Resolved relative to this file at runtime rather than imported statically:
 * a static `import '../../package.json'` would pull the file into the
 * compilation and push `rootDir` above `src/`, changing the whole emitted
 * output layout. The relative depth is the same in both contexts —
 * `src/core/` in dev via tsx, `dist/core/` once published — and npm always
 * ships package.json at the package root.
 */
function readPackageVersion(): string {
  try {
    const pkg = require('../../package.json') as { version?: string };
    return pkg.version ?? UNKNOWN_VERSION;
  } catch {
    return UNKNOWN_VERSION;
  }
}

export const TOOL_VERSION = readPackageVersion();

/** The single-source-of-truth directory holding the user's authored rules. */
export const SSOT_DIR = '.codebuddy';
export const CONFIG_FILE = 'config.json';

/**
 * Stamped into every generated file. `clean` and the stale-rule collector use
 * its presence to decide what this tool owns, which is what guarantees a
 * hand-written rule in an agent folder is never deleted.
 *
 * DO NOT CHANGE THIS STRING. Files already generated in the wild carry it;
 * changing it orphans every one of them — they become invisible to `clean` and
 * to garbage collection, and no later version can ever tidy them up.
 */
export const WATERMARK = `<!-- @generated by ${TOOL_NAME} -->`;

/** Delimiters for the managed block this tool owns inside .gitignore. */
export const GITIGNORE_START = '# --- Create Code Buddy (Start) ---';
export const GITIGNORE_END = '# --- Create Code Buddy (End) ---';

/**
 * The cross-agent convention file, read natively by Codex, Cursor, Copilot,
 * Gemini CLI, Aider, Devin Desktop, Zed and others. Notably NOT read by
 * Claude Code, which reads CLAUDE.md — bridged with a one-line `@AGENTS.md`
 * import, documented in the README rather than written for the user, since
 * anyone selecting the `claude` agent already gets properly path-scoped
 * rules in `.claude/rules/` and doesn't need the pointer.
 */
export const AGENTS_MD_FILE = 'AGENTS.md';

/**
 * Delimiters for the managed block inside AGENTS.md. Same approach as
 * .gitignore: this file is frequently hand-written, so only the block
 * between these markers is ever rewritten, and everything around it is left
 * exactly as the author left it.
 */
export const AGENTS_MD_START = '<!-- create-code-buddy:start -->';
export const AGENTS_MD_END = '<!-- create-code-buddy:end -->';

/**
 * The postinstall script `generator.ts` writes and `clean.ts` looks for
 * before removing. Shared so the two can never drift from each other —
 * `clean --hard` deletes a postinstall entry only on an exact string match.
 */
export const POSTINSTALL_SCRIPT = `npx ${TOOL_NAME} sync`;

/** Extensions treated as rule files, in the SSOT and in compiled output. */
export const RULE_EXTENSIONS = ['.md', '.mdc'] as const;
