/**
 * Single source of truth for every literal that identifies this tool on disk.
 *
 * Routing user-visible names through here means a future rename is a change to
 * these constants plus a watermark migration, rather than a find-and-replace
 * across every source file.
 */

export const TOOL_NAME = 'create-code-buddy';
export const TOOL_BIN = 'ccb';

/** The single-source-of-truth directory holding the user's authored rules. */
export const SSOT_DIR = '.codebuddy';
export const CONFIG_FILE = 'config.json';

/**
 * Stamped into every generated file. `clean` and the stale-rule collector use
 * its presence to decide what this tool owns, which is what guarantees a
 * hand-written rule in an agent folder is never deleted.
 *
 * DO NOT CHANGE THIS STRING. Files already generated in the wild carry it;
 * changing it orphans every one of them — they become invisible to `clean` and
 * to garbage collection, and no later version can ever tidy them up.
 */
export const WATERMARK = `<!-- @generated by ${TOOL_NAME} -->`;

/** Delimiters for the managed block this tool owns inside .gitignore. */
export const GITIGNORE_START = '# --- Create Code Buddy (Start) ---';
export const GITIGNORE_END = '# --- Create Code Buddy (End) ---';

/** Extensions treated as rule files, in the SSOT and in compiled output. */
export const RULE_EXTENSIONS = ['.md', '.mdc'] as const;
