import { describe, it, expect, vi, beforeEach } from 'vitest';
import { cleanAgents } from './clean';
import fs from 'fs';
import * as sync from './sync';
import { confirm, multiselect } from '@clack/prompts';

vi.mock('fs');
vi.mock('./sync');
vi.mock('@clack/prompts', () => ({
  confirm: vi.fn(),
  multiselect: vi.fn(),
  isCancel: vi.fn(() => false)
}));
vi.mock('picocolors', () => ({
  default: {
    green: vi.fn(s => s),
    red: vi.fn(s => s),
    yellow: vi.fn(s => s),
    white: vi.fn(s => s),
    cyan: vi.fn((s: string) => s),
    blue: vi.fn(s => s),
    magenta: vi.fn(s => s),
    dim: vi.fn(s => s),
    bold: vi.fn(s => s),
  }
}));

describe('cleanAgents', () => {
  beforeEach(() => {
    vi.resetAllMocks();
  });

  it('should cancel smart clean when user cancels folder selection', async () => {
    vi.mocked(fs.existsSync).mockReturnValue(true);
    vi.mocked(multiselect).mockResolvedValue([]);
    await cleanAgents('/fake/path');
    expect(fs.unlinkSync).not.toHaveBeenCalled();
  });

  it('should only delete watermarked files in smart clean, skip personal ones', async () => {
    const WATERMARK = '<!-- @generated by create-code-buddy -->';
    vi.mocked(multiselect).mockResolvedValue(['.cursor/rules']);
    vi.mocked(confirm).mockResolvedValue(true);
    vi.mocked(fs.existsSync).mockReturnValue(true);
    vi.mocked(fs.readdirSync).mockReturnValue([
      { name: 'generated.mdc', isDirectory: () => false } as any,
      { name: 'personal.mdc', isDirectory: () => false } as any,
    ]);
    vi.mocked(fs.readFileSync).mockImplementation((filePath) => {
      if ((filePath as string).includes('generated')) return `${WATERMARK}\n# Generated`;
      return '# My personal rule — no watermark';
    });

    await cleanAgents('/fake/path');

    // Only the watermarked file should be deleted
    expect(fs.unlinkSync).toHaveBeenCalledTimes(1);
    expect(fs.unlinkSync).toHaveBeenCalledWith(expect.stringContaining('generated.mdc'));
    expect(fs.unlinkSync).not.toHaveBeenCalledWith(expect.stringContaining('personal.mdc'));
  });

  it('should show nothing-to-delete message when no watermarked files exist', async () => {
    vi.mocked(multiselect).mockResolvedValue(['.cursor/rules']);
    vi.mocked(fs.existsSync).mockReturnValue(true);
    vi.mocked(fs.readdirSync).mockReturnValue([
      { name: 'personal.mdc', isDirectory: () => false } as any,
    ]);
    vi.mocked(fs.readFileSync).mockReturnValue('# My personal rule');

    await cleanAgents('/fake/path');

    expect(fs.unlinkSync).not.toHaveBeenCalled();
    expect(confirm).not.toHaveBeenCalled();
  });

  it('should run --hard reset: delete all 7 folders after double confirmation', async () => {
    vi.mocked(confirm)
      .mockResolvedValueOnce(true)  // first warning
      .mockResolvedValueOnce(true); // second warning
    vi.mocked(fs.existsSync).mockReturnValue(false); // no .codebuddy to backup

    await cleanAgents('/fake/path', true);

    // 6 compiled folders + .codebuddy = 7 potential targets (existsSync returns false so none are actually deleted)
    expect(confirm).toHaveBeenCalledTimes(2);
    expect(sync.updateGitignore).toHaveBeenCalled();
  });

  it('should cancel --hard reset on first confirmation denial', async () => {
    vi.mocked(confirm).mockResolvedValueOnce(false);
    await cleanAgents('/fake/path', true);
    expect(fs.rmSync).not.toHaveBeenCalled();
    expect(confirm).toHaveBeenCalledTimes(1);
  });

  it('should cancel --hard reset on second confirmation denial', async () => {
    vi.mocked(confirm)
      .mockResolvedValueOnce(true)
      .mockResolvedValueOnce(false);
    await cleanAgents('/fake/path', true);
    expect(fs.rmSync).not.toHaveBeenCalled();
    expect(confirm).toHaveBeenCalledTimes(2);
  });
});


