import fs from 'fs';
import path from 'path';
import pc from 'picocolors';
import { confirm, multiselect, isCancel } from '@clack/prompts';
import { updateGitignore } from './sync';

const WATERMARK = '<!-- @generated by create-code-buddy -->';

const AGENT_FOLDERS = [
  { value: '.claude/rules',        label: `Claude Code      ${pc.dim(pc.yellow('(.claude/rules)'))}` },
  { value: '.clinerules',          label: `Cline            ${pc.dim(pc.blue('(.clinerules)'))}` },
  { value: '.cursor/rules',        label: `Cursor           ${pc.dim(pc.cyan('(.cursor/rules)'))}` },
  { value: '.agents',              label: `Gemini           ${pc.dim(pc.magenta('(.agents)'))}` },
  { value: '.github/instructions', label: `GitHub Copilot   ${pc.dim(pc.green('(.github/instructions)'))}` },
  { value: '.windsurf/rules',      label: `Windsurf         ${pc.dim(pc.blue('(.windsurf/rules)'))}` },
];

function getMarkdownFiles(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  let results: string[] = [];
  const list = fs.readdirSync(dir, { withFileTypes: true });
  for (const item of list) {
    const fullPath = path.join(dir, item.name);
    if (item.isDirectory()) {
      results = results.concat(getMarkdownFiles(fullPath));
    } else if (item.name.endsWith('.md') || item.name.endsWith('.mdc')) {
      results.push(fullPath);
    }
  }
  return results;
}

function pruneEmptyDirs(dir: string, root: string) {
  if (!fs.existsSync(dir) || dir === root) return;
  const entries = fs.readdirSync(dir);
  if (entries.length === 0) {
    fs.rmdirSync(dir);
    pruneEmptyDirs(path.dirname(dir), root);
  }
}

export async function cleanAgents(projectRoot: string, isHard: boolean = false) {
  if (isHard) {
    // ── HARD RESET ──────────────────────────────────────────────
    const codebuddyDir = path.join(projectRoot, '.codebuddy');
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
    const backupName = `.codebuddy-backup-${timestamp}.tar.gz`;

    console.log(pc.yellow('\n  ⚠️  WARNING: Factory Reset\n'));
    console.log(pc.white('  This will permanently delete:'));
    console.log(pc.dim('    • All compiled agent folders (.cursor/rules, .agents, .clinerules, etc.)'));
    console.log(pc.dim('    • Your .codebuddy/ source folder and ALL rules inside it'));
    console.log(pc.dim('    • The postinstall script from package.json'));
    if (fs.existsSync(codebuddyDir)) {
      console.log(pc.dim(`\n  A backup will be created first at: `) + pc.cyan(backupName));
    }
    console.log('');

    const firstConfirm = await confirm({ message: 'Are you absolutely sure you want to factory reset everything?' });
    if (isCancel(firstConfirm) || !firstConfirm) {
      console.log(pc.yellow('Factory reset cancelled.'));
      return;
    }

    const secondConfirm = await confirm({ message: pc.red('Last chance — this cannot be undone. Proceed?') });
    if (isCancel(secondConfirm) || !secondConfirm) {
      console.log(pc.yellow('Factory reset cancelled.'));
      return;
    }

    // Create tar.gz backup before nuking
    if (fs.existsSync(codebuddyDir)) {
      try {
        const { execSync } = await import('child_process');
        const backupPath = path.join(projectRoot, backupName);
        execSync(`tar -czf "${backupPath}" -C "${projectRoot}" .codebuddy`);
        console.log(pc.green(`\n  ✔ Backup created: `) + pc.cyan(backupName));
        updateGitignore(projectRoot, ['*.codebuddy-backup.tar.gz'], false);
      } catch {
        console.log(pc.yellow('  Warning: Could not create backup. Proceeding anyway.'));
      }
    }

    // Nuke all compiled folders + .codebuddy
    const allFolders = [...AGENT_FOLDERS.map(f => f.value), '.codebuddy'];
    let deletedCount = 0;
    for (const folder of allFolders) {
      const dirPath = path.join(projectRoot, folder);
      if (fs.existsSync(dirPath)) {
        try {
          fs.rmSync(dirPath, { recursive: true, force: true });
          console.log(pc.dim(`  Deleted ${folder}`));
          deletedCount++;
        } catch {
          console.log(pc.yellow(`  Warning: Could not delete ${folder}. It may be locked by another process.`));
        }
      }
    }

    updateGitignore(projectRoot, [], true);
    console.log(pc.dim('  Cleaned .gitignore entries'));

    const pkgPath = path.join(projectRoot, 'package.json');
    if (fs.existsSync(pkgPath)) {
      try {
        const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
        if (pkg.scripts?.postinstall === 'npx create-code-buddy sync') {
          delete pkg.scripts.postinstall;
          if (Object.keys(pkg.scripts).length === 0) delete pkg.scripts;
          fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
          console.log(pc.dim('  Cleaned postinstall script from package.json'));
        }
      } catch {
        console.log(pc.yellow('  Warning: Could not parse package.json to remove postinstall.'));
      }
    }

    console.log(pc.green(`\n✔ Factory reset complete. ${deletedCount} folders deleted.\n`));
    return;
  }

  // ── SMART CLEAN ─────────────────────────────────────────────
  const existingFolders = AGENT_FOLDERS.filter(f => fs.existsSync(path.join(projectRoot, f.value)));

  if (existingFolders.length === 0) {
    console.log(pc.yellow('\n  No compiled agent folders found to clean.\n'));
    return;
  }

  const selectedFolders = await multiselect({
    message: 'Select the agent folders where you want to delete Code Buddy\'s generated rules:',
    options: existingFolders,
    initialValues: existingFolders.map(f => f.value),
    required: false,
  });

  if (isCancel(selectedFolders) || (selectedFolders as string[]).length === 0) {
    console.log(pc.yellow('Clean cancelled.'));
    return;
  }

  // Build preview — scan each folder for watermarked vs personal files
  const targets = selectedFolders as string[];
  const preview: { folder: string; toDelete: string[]; toSkip: number }[] = [];

  for (const folder of targets) {
    const dirPath = path.join(projectRoot, folder);
    const files = getMarkdownFiles(dirPath);
    const toDelete: string[] = [];
    let toSkip = 0;
    for (const file of files) {
      const content = fs.readFileSync(file, 'utf8');
      if (content.includes(WATERMARK)) {
        toDelete.push(file);
      } else {
        toSkip++;
      }
    }
    if (toDelete.length > 0 || toSkip > 0) {
      preview.push({ folder, toDelete, toSkip });
    }
  }

  // Print the preview summary
  console.log('');
  console.log(pc.white('  Here\'s what will happen:\n'));
  if (preview.length === 0) {
    console.log(pc.dim('  Nothing to delete — no generated files found in the selected folders.'));
    return;
  }
  for (const p of preview) {
    const deleteMsg = p.toDelete.length > 0
      ? pc.red(`${p.toDelete.length} generated file${p.toDelete.length > 1 ? 's' : ''} will be deleted`)
      : pc.dim('nothing to delete');
    const skipMsg = p.toSkip > 0
      ? pc.green(`, ${p.toSkip} personal file${p.toSkip > 1 ? 's' : ''} will be skipped`)
      : '';
    console.log(`  ${pc.cyan(p.folder.padEnd(28))}${deleteMsg}${skipMsg}`);
  }
  console.log(pc.dim('\n  Your personal rules (no watermark) will never be touched.\n'));

  const totalToDelete = preview.reduce((acc, p) => acc + p.toDelete.length, 0);
  if (totalToDelete === 0) {
    console.log(pc.dim('  Nothing generated to delete — any personal rules shown above are safe.\n'));
    return;
  }

  const shouldClean = await confirm({ message: 'Delete these generated files?' });
  if (isCancel(shouldClean) || !shouldClean) {
    console.log(pc.yellow('Clean cancelled.'));
    return;
  }

  // Execute deletions — watermarked files only
  let deletedCount = 0;
  for (const p of preview) {
    for (const file of p.toDelete) {
      try {
        fs.unlinkSync(file);
        deletedCount++;
        pruneEmptyDirs(path.dirname(file), path.join(projectRoot, p.folder));
      } catch {
        console.log(pc.yellow(`  Warning: Could not delete ${file}. It may be locked.`));
      }
    }
  }

  updateGitignore(projectRoot, [], true);
  console.log(pc.dim('\n  Cleaned .gitignore entries'));
  console.log(pc.green(`\n✔ Cleaned ${deletedCount} generated file${deletedCount !== 1 ? 's' : ''}.\n`));
}


