import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { migrate, planMigration } from './migrate';
import { syncAgents } from './sync';
import {
  makeWorkspace,
  cleanupWorkspaces,
  writeFile,
  readFile,
  exists,
  ruleFile,
} from './test/workspace';

/**
 * Covers the upgrade path for anyone whose rules sit directly in
 * `.codebuddy/`, from before `rules/` existed.
 *
 * The property that matters most is that nothing moves without being asked:
 * this restructures a folder the user keeps in version control, so a dry run
 * is the default and `sync` never triggers it.
 */

const RULE = ruleFile('Testing standards', ['*.test.ts']);
const CONFIG = JSON.stringify({ agents: ['cursor'], gitignore_compiled_agents: true }, null, 2);

/** A workspace in the old layout: rules loose at the top of `.codebuddy/`. */
function legacyWorkspace(): string {
  const root = makeWorkspace();
  writeFile(root, '.codebuddy/config.json', CONFIG);
  writeFile(root, '.codebuddy/testing.md', RULE);
  writeFile(root, '.codebuddy/backend/database.md', ruleFile('DB rules', ['*.sql']));
  return root;
}

let exitCodeBefore: typeof process.exitCode;

beforeEach(() => {
  exitCodeBefore = process.exitCode;
  vi.spyOn(console, 'log').mockImplementation(() => {});
  vi.spyOn(console, 'error').mockImplementation(() => {});
});

afterEach(() => {
  process.exitCode = exitCodeBefore;
  vi.restoreAllMocks();
  cleanupWorkspaces();
});

describe('migrate', () => {
  it('moves nothing without --apply', async () => {
    const root = legacyWorkspace();

    await migrate(root);

    expect(exists(root, '.codebuddy/testing.md')).toBe(true);
    expect(exists(root, '.codebuddy/rules/testing.md')).toBe(false);
  });

  it('moves rules into rules/, keeping nesting', async () => {
    const root = legacyWorkspace();

    await migrate(root, true);

    expect(exists(root, '.codebuddy/rules/testing.md')).toBe(true);
    expect(exists(root, '.codebuddy/rules/backend/database.md')).toBe(true);
    expect(exists(root, '.codebuddy/testing.md')).toBe(false);
    expect(readFile(root, '.codebuddy/rules/testing.md')).toContain('Testing standards');
  });

  it('leaves config.json where it belongs', async () => {
    const root = legacyWorkspace();

    await migrate(root, true);

    expect(exists(root, '.codebuddy/config.json')).toBe(true);
    expect(exists(root, '.codebuddy/rules/config.json')).toBe(false);
  });

  it('leaves specs alone — they are already in the right place', async () => {
    const root = legacyWorkspace();
    writeFile(root, '.codebuddy/specs/v1.md', '---\ndescription: V1\n---\n\n# V1');

    await migrate(root, true);

    expect(exists(root, '.codebuddy/specs/v1.md')).toBe(true);
    expect(exists(root, '.codebuddy/rules/specs/v1.md')).toBe(false);
  });

  it('is idempotent — a second run has nothing to do', async () => {
    const root = legacyWorkspace();
    await migrate(root, true);

    expect(planMigration(root)).toEqual([]);
    await migrate(root, true);

    expect(exists(root, '.codebuddy/rules/testing.md')).toBe(true);
  });

  it('refuses rather than overwriting when both layouts hold the same file', async () => {
    const root = legacyWorkspace();
    writeFile(root, '.codebuddy/rules/testing.md', 'already here');

    await migrate(root, true);

    // Picking a winner silently would lose somebody's work.
    expect(readFile(root, '.codebuddy/rules/testing.md')).toBe('already here');
    expect(exists(root, '.codebuddy/testing.md')).toBe(true);
    expect(process.exitCode).toBe(1);
  });

  it('fails clearly when there is no .codebuddy at all', async () => {
    const root = makeWorkspace();

    await migrate(root, true);

    expect(process.exitCode).toBe(1);
  });
});

describe('the full upgrade path', () => {
  it('sync refuses first, then migrate fixes it, then output is restored', async () => {
    // Start in the old layout WITH compiled output, exactly as someone who
    // installed an earlier version would be.
    const root = legacyWorkspace();
    writeFile(root, '.cursor/rules/testing.mdc', `<!-- @generated by create-code-buddy -->\n# old`);

    // 1. sync must refuse and delete nothing.
    await syncAgents(root);
    expect(process.exitCode).toBe(1);
    expect(exists(root, '.cursor/rules/testing.mdc')).toBe(true);

    // 2. migrate moves the rules.
    process.exitCode = 0;
    await migrate(root, true);
    expect(exists(root, '.codebuddy/rules/testing.md')).toBe(true);

    // 3. sync now works, and compiles to the same paths as always.
    await syncAgents(root);
    expect(exists(root, '.cursor/rules/testing.mdc')).toBe(true);
    expect(exists(root, '.cursor/rules/backend/database.mdc')).toBe(true);
    expect(readFile(root, '.cursor/rules/testing.mdc')).toContain('Testing standards');
  });
});
