import { describe, it, expect, vi, beforeEach } from 'vitest';
import { syncAgents, updateGitignore } from './sync';
import fs from 'fs';
import path from 'path';

vi.mock('fs');
vi.mock('picocolors', () => ({
  default: {
    green: vi.fn(s => s),
    red: vi.fn(s => s),
    cyan: vi.fn(s => s),
    dim: vi.fn(s => s)
  }
}));

describe('syncAgents', () => {
  beforeEach(() => {
    vi.resetAllMocks();
  });

  it('should exit if no config is found', async () => {
    vi.mocked(fs.existsSync).mockReturnValue(false);
    await syncAgents('/fake/path');
    expect(fs.readFileSync).not.toHaveBeenCalled();
  });

  it('should compile rules for selected agents', async () => {
    vi.mocked(fs.existsSync).mockReturnValue(true);
    vi.mocked(fs.readFileSync).mockImplementation((pathStr: any) => {
      if ((pathStr as string).endsWith('config.json')) {
        return JSON.stringify({ agents: ['cursor', 'gemini'], gitignore_compiled_agents: true });
      }
      return '---\ndescription: Test\nglobs: ["*.ts"]\n---\n# Content';
    });
    vi.mocked(fs.readdirSync).mockReturnValue([
      { name: 'test.md', isDirectory: () => false } as any
    ]);

    await syncAgents('/fake/path');

    // Should create cursor MDC
    expect(fs.writeFileSync).toHaveBeenCalledWith(
      path.join('/fake/path', '.cursor/rules/test.mdc'),
      '---\ndescription: Test\nglobs: ["*.ts"]\n---\n<!-- @generated by create-code-buddy -->\n# Content'
    );

    // Should create gemini MD
    expect(fs.writeFileSync).toHaveBeenCalledWith(
      path.join('/fake/path', '.agents/rules/test.md'),
      '---\ndescription: Test\nglobs: ["*.ts"]\n---\n<!-- @generated by create-code-buddy -->\n# Content'
    );
  });

  it('should compile Windsurf rules with standard frontmatter', async () => {
    vi.mocked(fs.existsSync).mockReturnValue(true);
    vi.mocked(fs.readFileSync).mockImplementation((pathStr: any) => {
      if ((pathStr as string).endsWith('config.json')) {
        return JSON.stringify({ agents: ['windsurf'], gitignore_compiled_agents: true });
      }
      return '---\ndescription: Test\nglobs: ["*.ts"]\n---\n# Content';
    });
    vi.mocked(fs.readdirSync).mockReturnValue([
      { name: 'test.md', isDirectory: () => false } as any
    ]);

    await syncAgents('/fake/path');

    expect(fs.writeFileSync).toHaveBeenCalledWith(
      path.join('/fake/path', '.windsurf/rules/test.md'),
      '---\ndescription: Test\nglobs: ["*.ts"]\n---\n<!-- @generated by create-code-buddy -->\n# Content'
    );
  });

  it('should compile Cline rules omitting frontmatter for always-on rules', async () => {
    vi.mocked(fs.existsSync).mockReturnValue(true);
    vi.mocked(fs.readFileSync).mockImplementation((pathStr: any) => {
      if ((pathStr as string).endsWith('config.json')) {
        return JSON.stringify({ agents: ['cline'], gitignore_compiled_agents: true });
      }
      return '---\ndescription: Always on\nglobs: "*.*"\n---\n# Content';
    });
    vi.mocked(fs.readdirSync).mockReturnValue([
      { name: 'architecture.md', isDirectory: () => false } as any
    ]);

    await syncAgents('/fake/path');

    // Always-on rules should have NO frontmatter in Cline
    expect(fs.writeFileSync).toHaveBeenCalledWith(
      path.join('/fake/path', '.clinerules/architecture.md'),
      '<!-- @generated by create-code-buddy -->\n# Content'
    );
  });

  it('should compile Cline rules converting globs to paths: block format', async () => {
    vi.mocked(fs.existsSync).mockReturnValue(true);
    vi.mocked(fs.readFileSync).mockImplementation((pathStr: any) => {
      if ((pathStr as string).endsWith('config.json')) {
        return JSON.stringify({ agents: ['cline'], gitignore_compiled_agents: true });
      }
      return '---\ndescription: Test\nglobs: ["*.test.*", "*.spec.*"]\n---\n# Content';
    });
    vi.mocked(fs.readdirSync).mockReturnValue([
      { name: 'testing.md', isDirectory: () => false } as any
    ]);

    await syncAgents('/fake/path');

    expect(fs.writeFileSync).toHaveBeenCalledWith(
      path.join('/fake/path', '.clinerules/testing.md'),
      '---\npaths:\n  - "**/*.test.*"\n  - "**/*.spec.*"\n---\n<!-- @generated by create-code-buddy -->\n# Content'
    );
  });

  it('should compile Copilot rules with .instructions.md extension and applyTo frontmatter', async () => {
    vi.mocked(fs.existsSync).mockReturnValue(true);
    vi.mocked(fs.readFileSync).mockImplementation((pathStr: any) => {
      if ((pathStr as string).endsWith('config.json')) {
        return JSON.stringify({ agents: ['copilot'], gitignore_compiled_agents: true });
      }
      return '---\ndescription: Test\nglobs: ["*.ts"]\n---\n# Content';
    });
    vi.mocked(fs.readdirSync).mockReturnValue([
      { name: 'architecture.md', isDirectory: () => false } as any
    ]);

    await syncAgents('/fake/path');

    expect(fs.writeFileSync).toHaveBeenCalledWith(
      path.join('/fake/path', '.github/instructions/architecture.instructions.md'),
      '---\napplyTo: "*.ts"\n---\n<!-- @generated by create-code-buddy -->\n# Content'
    );
  });
});

describe('updateGitignore', () => {
  it('should inject gitignore block safely', () => {
    vi.mocked(fs.existsSync).mockReturnValue(true);
    vi.mocked(fs.readFileSync).mockReturnValue('node_modules/\n');

    updateGitignore('/fake/path', ['.cursor/']);

    expect(fs.writeFileSync).toHaveBeenCalledWith(
      path.join('/fake/path', '.gitignore'),
      'node_modules/\n\n# --- Create Code Buddy (Start) ---\n.cursor/\n# --- Create Code Buddy (End) ---\n'
    );
  });
});
